### ISSUE TITLE
Interface nuxed\Contract\Util\Jsonable is not \JsonSerializable

### ISSUE THREAD

**Issue by lexidor** [nuxed/framework#22]
PHP has a default built interface that does this for you, but instead of needing the return a encoded string, it returns the array/object to be encoded.

This allows you to nest JsonSerializable objects.

```php
<?php
class A implements JsonSerializable{
    public $foo;

    public function jsonSerialize(){
        return [
            'afoo' => $this->foo
        ];
    }
}

class B implements JsonSerializable{
    public $arrayOfA;
    public $foo;

    public function jsonSerialize(){
        return [
            'As' => $this->arrayOfA,
            'bfoo' => $this->foo
        ];
    }
}

echo json_encode(
    (new B())->arrayOfA = [new A(), new A()]
);

// {"As":[{"afoo": null},{"afoo": null}],"bfoo":null}
```

**Comment by azjezz** [comment]
The `Nuxed\Contract\Util\Jsonable` interface was meant for `Nuxed\Util\Json::encode`, and you shouldn't use `json_encode` / `json_decode` functions ( or any other PHP-legacy functions ) with Nuxed.

as you can see here : https://github.com/nuxed/framework/blob/master/src/Nuxed/Util/Json.hack#L19
an object that is `Jsonable` should be able to encode itself.
example : 

```hack
use type Nuxed\Contract\Util\Jsonable;
use type Nuxed\Util\Json;

class Foo<Tk, Tv> implements Jsonable {
  public function __construct(
    private KeyedContainer<Tk, Tv> $data
  ) {}

  public function toJson(bool $pretty = false): string {
    return Json::encode($this->data, $pretty);
  }
}
```

**Comment by lexidor** [comment]
I would strongly recommend to take a look at this again.
```
    if ($value is Jsonable) {
      return $value->toJson($pretty);
    }

    $flags = JSON_UNESCAPED_UNICODE |
      JSON_UNESCAPED_SLASHES |
      JSON_PRESERVE_ZERO_FRACTION;
    if ($pretty) {
      $flags |= JSON_PRETTY_PRINT;
    }

$json = json_encode($value, $flags);
```
The PHP json_encode will encode an iterable of JsonSerializable by calling jsonSerialize() on each object. This results in [$obj, $obj] to be encoded as:
```
[
  {"A": 1},
  {"B": 2}
]
```
Using Jsonable this would result in an error. "Object could not be json encoded."

Yes, if you pass object directly, it would call toJson(), but this simple usecase would nolonger be supported.

**Comment by lexidor** [comment]
The real strength of `JsonSerializable` lies in the fact that you can compose various levels of encoding. For example class A has a property $b of type B. B is JsonSerializable. A wants to be JsonSerializable too and wishes to include the encoded $b property in its encoded form. A can simple accomplish this by returning`['B' => $this->b, ...]` from jsonSerialize. The fact that these methods return the structure to be encoded instead of the encoded string, allows for nest without double encoding the B object. I hope you understand my concerns while this project still has the room to change.

**Comment by azjezz** [comment]
@Lexidor  `json_encode` it self is not used and won't be mentioned anywhere in nuxed, instead use `Nuxed\Util\Json::encode`

in case `Json::encode(vec[$a, $b]);`, yes, `toJson` won't be called.

we might add a `JsonableTrait` similar to the `StringableTrait` that exists to do the following ( would save the developer by needing to implement 1 method instead of 2 ) : 
```hack
namespace Nuxed\Util;

use type Nuxed\Contract\Util\Jsonable;
use type JsonSerializable;

trait JsonableTrait<T> implements Jsonable, JsonSerializable {
  public function toJson(bool $pretty = true): string {
    return Json::encode($this->jsonSerialize(), $pretty);
  }

  abstract public function jsonSerialize(): T;
}
```

but making `Jsonable` itself `JsonSerializable` won't happen, as its meant to be used with single object ( the common use case ). i'm not sure about the future of the json extension in hhvm and would need to ask around. but i don't think `JsonSerializable` is going to stay as its untyped.

the point of `Jsonable` is to be able to convert object to json yourself without needing to call `Json::encode()`, example : 


```hack

$ast = parse($code);
if ($ast is Jsonable) {
  print $ast->toJson(true);
  exit(0);
} else {
  // encode `$ast` yourself.
}
```

**Comment by lexidor** [comment]
Okay, so Jsonable is an interface for convenience. It allows objects to intercept call made from Json::encode(). HHVM might kill JsonSerializable, but they also might not. Since typing its return doesn't give you much. I'll close this issue, since I have said everything that I wanted to say.
